version: '3'

services:
  dj:
    image: jekyll/jekyll:4
    container_name: dj
    ports:
      - 4000:4000
    volumes:
      - ./:/srv/jekyll
    environment:
      JEKYLL_VERSION: 4.1.1
    command: jekyll serve --verbose --force_polling
